### ISSUE TITLE
리스트에 보여지는 메시지들 실시간성이 떨어짐. 

### ISSUE THREAD

**Issue by yeojin78** [dodotdo/hims-web-angular#10]
메시지가 온지 얼마나 지났는지 시간도 새로고침해야 업데이트 되고 때문에 none상태에서 10분 지나면 배경이 색 바껴야하는데 이것도 새로고침해야지 나옴.

**Comment by seokju-na** [comment]
Fixed: 1분마다 새로고침 타이머 기능 추가
